jwt:
    time: 1000
    secret: hello-posco

posco:
    name: 3기default
    count: 20
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: gonggu
        password: 1234
