jwt:
    time: 900000546321
    secret: hello-world423145
posco:
    name: 3기prd
    count: 20
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: 1234

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&amp
        characterEncoding: UTF-8
        username: root
        password: "{cipher}b1b96922f7fdd57132f2c38cf7ad746921809a94fa2255eba490bdd4746a934e"
